# Schema for the configuration files of the idp_insights module.
idp_insights.settings:
  type: config_object
  label: "IDP Indights settings"
  mapping:
    api_key:
      type: string
      label: "API Key"
